### ISSUE TITLE
Feature Suggestion: Creating your own preferred return order upon inspection

### ISSUE THREAD

**Issue by Morteee** [SaltyMonkey/moongourd-spy#1]
I was in the process of trying to modify which dungeons the mod would return upon inspection. I was able to easily change which dungeons it returned but not the order. I'll attach my specific settings here:
![settings](https://user-images.githubusercontent.com/70561298/91796805-b3d04e00-ebe6-11ea-8bb6-e49a96f4ff79.JPG)

The order it seemed to consistently return was Bahaar>DAH>FA>AQ>DAN. I inspected multiple people multiple times and that was the order every time, even when someone wouldn't have valid runs for one of the categories. 

I had asked in the Toolbox discord if anyone knew how to fix it and Caali said I had done basically all I could and that it was probably either Moongourd's response times or the mod's processing time. They also gave this suggestion:
>"it should be a simple fix, instead of printing all stuff as soon as it's computed he can just return the resulting data from the async function and await the entire list he's currently forEach()ing. smth like await Promise.all(continentsToCheck.map(x => analyzeChar(...)), and then print it afterwards in proper order"

Thank you, I really appreciate this mod a ton. Was really disappointed that the last in-line inspector mod broke with the new moongourd but this one is way better.

**Comment by SaltyMonkey** [comment]
done
